### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/mileslane/Projects/ocm-cds-tools...

### ISSUE THREAD

**Issue by mileslane** [tomkadwill/atom-cucumber-autocomplete#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.6.3
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/user/Projects/myproject/features'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/user/Projects/myproject/features'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.scanFeaturesDir (/Users/user/.atom/packages/cucumber-autocomplete/lib/provider.js:46:13)
    at Object.getCompletions (/Users/user/.atom/packages/cucumber-autocomplete/lib/provider.js:31:19)
    at Object.getSuggestions (/Users/user/.atom/packages/cucumber-autocomplete/lib/provider.js:17:17)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "ember-tabs"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
build-ember, v0.0.1
cucumber, v0.5.0
cucumber-autocomplete, v0.6.3
ember-cli-helper, v0.9.0
language-gherkin, v1.0.3
merge-conflicts, v1.4.2
open-unsupported-files, v1.0.19
pretty-json, v1.0.3

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @mileslane, did you get this working? You can override the default path to your features directory to point to the correct location

**Comment by mileslane** [comment]
I don't recall.  My team has two groups.  One uses Spinach and the other uses Turnip.  My study of Cucumber is a project for me to wrap my head around BDD and Gherkin.

**Comment by tomkadwill** [comment]
OK. Closing this for now. Please re-open, if you run into the bug again
