### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Github/calabash/features'

### ISSUE THREAD

**Issue by kailashmore** [tomkadwill/atom-cucumber-autocomplete#15]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.3
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.6.3
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Github/calabash/features'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Github/calabash/features'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.scanFeaturesDir (/Users/kailashm/.atom/packages/cucumber-autocomplete/lib/provider.js:46:13)
    at Object.getCompletions (/Users/kailashm/.atom/packages/cucumber-autocomplete/lib/provider.js:31:19)
    at Object.getSuggestions (/Users/kailashm/.atom/packages/cucumber-autocomplete/lib/provider.js:17:17)
    at /Users/kailashm/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/kailashm/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Users/kailashm/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/kailashm/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Users/kailashm/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -0:26 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:03.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-ruby, v0.1.0
cucumber, v0.5.0
cucumber-autocomplete, v0.6.3
language-gherkin-i18n, v1.3.4
ruby-syntax-replacer, v0.5.1

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @kailashmore, did you get this working? You can override the default path to your features directory to point to the correct location

**Comment by tomkadwill** [comment]
Closing. Please re-open if you are still seeing the bug
