### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\<UserName>\AppData\Local\atom\app-1.4.1\atom:\config\features'

### ISSUE THREAD

**Issue by choerl** [tomkadwill/atom-cucumber-autocomplete#2]
Enter steps to reproduce below:]

Opening a feature file
Writing a scenario
When typing a "Given", "When", And" or "Then" the error appears

Atom Version: 1.4.1
System: Windows 10
Thrown From: cucumber-autocomplete package, v0.2.0
# Stack Trace

Error: ENOENT: no such file or directory, scandir 'C:\Users<UserName>\AppData\Local\atom\app-1.4.1\atom:\config\features'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.module.exports.getCompletions (file:///C:/Users/<UserName>/.atom/packages/cucumber-autocomplete/lib/provider.coffee:28:5)
    at Object.module.exports.getSuggestions (file:///C:/Users/<UserName>/.atom/packages/cucumber-autocomplete/lib/provider.coffee:16:6)
    at C:\Users\C5199828\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\C5199828\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\C5199828\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\C5199828\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:256:19)
    at C:\Users\C5199828\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

Installed Packages
# User

behat-atom@0.1.2
capybara-snippets@0.2.0
cucumber@0.5.0
cucumber-autocomplete@0.2.0
cucumber-step@0.2.0
git-diff@0.57.0
git-difftool@0.2.7
github-web@1.1.0
language-gherkin@1.0.3
language-git@0.12.1
rspec@0.3.2
rspec-snippets@0.4.0
ruby-bundler@0.3.0
test-status@1.0.0
travis-ci-status@1.0.0
# Dev

No dev packages

**Comment by tomkadwill** [comment]
Hi @choerl, what is the file path of your features directory, in that project?

**Comment by choerl** [comment]
Hi @tomkadwill,

thanks for your reply.

the path to the project is 
C:\Users<UserName>\GitHub\cucumbertests\WARP_UI_Test\features\behavior_summary.feature

It contradicts with the path where the error is thrown 
C:\Users<UserName>\AppData\Local\atom\app-1.4.1\atom:\config\features

But I don't know where the error takes this path..

**Comment by tomkadwill** [comment]
Hmm.. Okay, I'm not on a windows machine so I will need to fire up a VM in order to reproduce and fix this.

If you can make a PR or provide any more information that would be much appreciated :blush:

**Comment by tomkadwill** [comment]
Hi @choerl, I haven't tested this on Windows specifically but I've added a fix for this in v0.7.1. Please re-open this issue if it has not been resolved in v0.7.1
