### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/ed.kierans/brainwahve/features'

### ISSUE THREAD

**Issue by eamonx** [tomkadwill/atom-cucumber-autocomplete#21]
[Enter steps to reproduce below:]
1. Start typing "And" - List appears
2. Do not choose anything in list and continue typing, eg QS
3. Error is thrown

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.3
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.7.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/ed.kierans/brainwahve/features'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/ed.kierans/brainwahve/features'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.scanFeaturesDir (/Users/ed.kierans/.atom/packages/cucumber-autocomplete/lib/provider.js:46:13)
    at Object.getCompletions (/Users/ed.kierans/.atom/packages/cucumber-autocomplete/lib/provider.js:31:19)
    at Object.getSuggestions (/Users/ed.kierans/.atom/packages/cucumber-autocomplete/lib/provider.js:17:17)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
  3x -0:13.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.3.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v1.2.13
cucumber-autocomplete, v0.7.0
jshint, v1.8.5
language-gherkin, v1.0.4
merge-conflicts, v1.4.3

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @eamonx, I've added a fix for this in v0.7.1. Please re-test re-open this issue if the problem still occurs in v0.7.1
