### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/root-user/Documenti/tysLab/features'

### ISSUE THREAD

**Issue by AnSlvt** [tomkadwill/atom-cucumber-autocomplete#22]
This appear every time I wrote something in a feature file 

```
Error:` ENOENT: no such file or directory, lstat '/home/root-user/Documenti/tysLab/features'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:228:16)
    at Object.scanFeaturesDir (/home/root-user/.atom/packages/cucumber-autocomplete/lib/provider.js:66:13)
    at Object.getCompletions (/home/root-user/.atom/packages/cucumber-autocomplete/lib/provider.js:49:19)
    at Object.getSuggestions (/home/root-user/.atom/packages/cucumber-autocomplete/lib/provider.js:35:17)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

**Comment by stephanebruckert** [comment]
Found in the README: 

> What does it scan? The package scans a directory of your choice, by default it scans the /features directory of your project. You override the default by changing the path option under settings.

But I agree the error should be handled.
