### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/kyle/Code/page-object-spike/fe...

### ISSUE THREAD

**Issue by kmckee** [tomkadwill/atom-cucumber-autocomplete#3]
First, thanks for creating this plugin.  It's awesome.  :)

I'm running into this error, occasionally.  It looks like it expects the 'features' folder to be in the root of my project.  

99% of the time I would agree that it should always be there, however, in my case I have a legitimate reason to keep it elsewhere.

If I finish up what I'm working on, I may try digging into this code to see if I can change it and send a PR.

Thanks!

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.3.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/kyle/Code/page-object-spike/features'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/kyle/Code/page-object-spike/features'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.module.exports.getCompletions (/Users/kyle/.atom/packages/cucumber-autocomplete/lib/provider.coffee:27:5)
    at Object.module.exports.getSuggestions (/Users/kyle/.atom/packages/cucumber-autocomplete/lib/provider.coffee:17:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -1:12.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:09.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:08.5.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:05.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:05.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:05.5.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:05.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -1:05.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:18.9.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:18.6.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:16.4.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:16 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:16 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:15.1.0 blur (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-js-standard",
      "linter-jshint",
      "linter-jsxhint",
      "linter-sass-lint",
      "jshint"
    ],
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.19.0
atom-material-ui, v0.8.1
atom-typescript, v8.2.0
autosave, v0.23.1
color-picker, v2.1.1
cucumber, v0.5.0
cucumber-autocomplete, v0.3.1
emmet, v2.4.1
ex-mode, v0.8.0
highlight-selected, v0.11.2
language-babel, v2.15.4
linter, v1.11.3
linter-eslint, v6.0.0
linter-htmlhint, v1.0.2
linter-ruby, v1.2.1
linter-tslint, v0.6.0
monokai, v0.18.0
node-debugger, v1.3.2
nodejs-snippets, v2.0.0
pretty-json, v0.4.1
seti-icons, v0.4.5
sync-settings, v0.6.0
terminal-status, v1.6.8
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
hey @kmckee, I'm glad you're find cucumber-autocomplete helpful :)

Thanks for reporting the bug, I'd like to get that fixed. If you go into the package settings you can change the default path for your `features` directory. Does that help with your problem?

**Comment by kmckee** [comment]
I never saw that in there, yes that definitely helps, thank you!

Should we just close this?  Or are you thinking of trying to auto detect it or something?

**Comment by tomkadwill** [comment]
Great! I might think about that in future but I'll close this issue for now as it seems to solve your problem

**Comment by kmckee** [comment]
👍thanks again!
