### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/gladstonp/Measure_test/feature...

### ISSUE THREAD

**Issue by Gladdy23** [tomkadwill/atom-cucumber-autocomplete#4]
[Enter steps to reproduce below:]
1. This error pops up every time I start typing into a feature file

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.4
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.4.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/gladstonp/Measure_test/features/features'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/gladstonp/Measure_test/features/features'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.module.exports.getCompletions (/Users/gladstonp/.atom/packages/cucumber-autocomplete/lib/provider.coffee:24:5)
    at Object.module.exports.getSuggestions (/Users/gladstonp/.atom/packages/cucumber-autocomplete/lib/provider.coffee:18:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -9:25.9.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -9:22.3.0 core:save (atom-text-editor.editor.is-focused)
  6x -6:55.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:39.6.0 core:move-right (atom-text-editor.editor.is-focused)
  7x -6:39.3.0 core:backspace (atom-text-editor.editor.is-focused)
 15x -6:13.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.22
cucumber, v0.5.0
cucumber-autocomplete, v0.4.0
language-gherkin, v1.0.3

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @Gladdy23, looks like the the plugin is searching for features in `'/features/features'` but it can't find anything there. Have you changed the path under cucumber-autocomplete settings?

**Comment by tomkadwill** [comment]
Closing this issue. Please re-open if this is still an issue
