### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/username/Desktop/features/step_defi...

### ISSUE THREAD

**Issue by isakib** [tomkadwill/atom-cucumber-autocomplete#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [cucumber-autocomplete](https://github.com/tomkadwill/atom-cucumber-autocomplete) package, v0.6.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/username/Desktop/features/step_definitions'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/username/Desktop/features/step_definitions'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.module.exports.getCompletions (/Users/username/.atom/packages/cucumber-autocomplete/lib/provider.coffee:25:16)
    at Object.module.exports.getSuggestions (/Users/username/.atom/packages/cucumber-autocomplete/lib/provider.coffee:19:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -0:03.3.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "cucumber-autocomplete": {}
}
```
### Installed Packages

``` coffee
# User
cucumber-autocomplete, v0.6.0
language-gherkin, v1.0.3

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @isakib, I've released a patch that should fix this problem. Please re-test and let me know whether v0.6.1 fixes the problem for you. Thanks!

**Comment by tomkadwill** [comment]
Closing this issue. Please re-open if the problem still occurs
